### ISSUE TITLE
cannot do npm start

### ISSUE THREAD

**Issue by malishahi** [mjrussell/redux-auth-wrapper#154]
ERROR in /home/mehdi/git/ReactJs/redux-auth-wrapper/src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "/home/mehdi/git/ReactJs/redux-auth-wrapper/.babelrc" at 0, attempted to resolve relative to "/home/mehdi/git/ReactJs/redux-auth-wrapper"
    at /home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/home/mehdi/git/ReactJs/redux-auth-wrapper/examples/basic/node_modules/babel-loader/index.js:131:12)

**Comment by mjrussell** [comment]
Did you follow the directions in the README and run npm install in the root of the project?
```
1. Install dependencies with `npm install` in this directory (make sure it creates a local node_modules)
2. By default, it uses the local version from `src` of redux-auth-wrapper, so you need to run `npm install` from there first.
3. `npm start`
4. `Browse to http://localhost:8080`
```

**Comment by malishahi** [comment]
Yes, when I start to run it gives me that error.

**Comment by mjrussell** [comment]
I just ran it, so I dont believe there is an issue. Please do the following:
```
cd home/mehdi/git/ReactJs/redux-auth-wrapper
git checkout master
rm -rf node_modules
npm install
cd examples/basic
rm -rf node_modules
npm install
npm start
```
Then browse to http://localhost:8080
