### ISSUE TITLE
the expample can't run

### ISSUE THREAD

**Issue by yinhezhu** [mjrussell/redux-auth-wrapper#156]
ERROR in /Users/yinhezhu/work/redux/redux-auth-wrapper/src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "/Users/yinhezhu/work/redux/redux-auth-wrapper/.babelrc" at 0, attempted to resolve relative to "/Users/yinhezhu/work/redux/redux-auth-wrapper"
    at /Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/yinhezhu/work/redux/redux-auth-wrapper/examples/loading/node_modules/babel-loader/index.js:131:12)
 @ ./app.js 29:24-53

**Comment by mjrussell** [comment]
See https://github.com/mjrussell/redux-auth-wrapper/issues/154
