### ISSUE TITLE
error demo v4

### ISSUE THREAD

**Issue by webmobiles** [mjrussell/redux-auth-wrapper#199]
after do 'npm install' and 'npm start' i get this error:

```


> raw-loading-rrv4-example@0.0.0 start /Users/cherdave/projects/redux-auth-wrapper/examples/react-router-4
> webpack-dev-server --config webpack.config.babel.js --progress

/Users/cherdave/projects/redux-auth-wrapper/examples/react-router-4/webpack.config.babel.js:70
  throw ''(_templateObject2)(_templateObject);
          ^

TypeError: "" is not a function
    at Object.<anonymous> (/Users/cherdave/projects/redux-auth-wrapper/examples/react-router-4/webpack.config.babel.js:58:3)
    at Module._compile (module.js:569:30)
    at loader (/Users/cherdave/projects/redux-auth-wrapper/examples/react-router-4/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/cherdave/projects/redux-auth-wrapper/examples/react-router-4/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/cherdave/projects/redux-auth-wrapper/examples/react-router-4/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/cherdave/projects/redux-auth-wrapper/examples/react-router-4/node_modules/webpack-dev-server/bin/webpack-dev-server.js:68:48)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raw-loading-rrv4-example@0.0.0 start: `webpack-dev-server --config webpack.config.babel.js --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-loading-rrv4-example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Comment by shai32** [comment]
Go to the root folder and do:
npm install
npm run build

**Comment by mjrussell** [comment]
I dont have any problems running the example when I follow the instructions in the react-router v4 example. Can you please verify these steps? Otherwise could be an npm version difference or a node version incompatibility...

```
Go to the root of this project (up two folders) and run npm install && npm run build
In this folder, run npm install
In this folder, npm start
Browse to http://localhost:8080
```

**Comment by gitjeff05** [comment]
It might be a good idea to clarify which paths to run the commands from. I got the demo working running ``npm install && npm build`` from ``examples/react-router-4``. Then ``npm install`` from the root folder. Then ``npm start`` from the ``examples/react-router-4`` folder.

Is that the intended interpretation?

Note that running ``npm install && npm run build`` from ``examples/react-router-4`` gives me an error ``Error: missing script: build``.

**Comment by mjrussell** [comment]
what you posted @gitjeff05 isn't quite right, it should be:

```bash
[yourpath/redux-auth-wrapper]$ npm install && npm run build
[yourpath/redux-auth-wrapper/examples/react-router-4]$ npm install 
[yourpath/redux-auth-wrapper/examples/react-router-4]$ npm start
```
How can I improve the docs to make this more clear?

**Comment by usefksa** [comment]
you should do the following:
```
cd redux-auth-wrapper/examples/react-router-4
npm install
npm start
```

then open
http://localhost:8080/

It worked for me.

**Comment by mjrussell** [comment]
I've removed the ES6 templating in the webpack config and should now print the error regardless of ES6, about needing to run the npm build. Hopefully this solves that issue
